### ISSUE TITLE
Failed to run the test

### ISSUE THREAD

**Issue by Andy-AO** [KubaP/Powershell-Symlink#10]
Want to add tests to prepare for bug repair.

Call `pester.ps1` And found that almost all the tests failed.

`TerminatingError(): "478 / 555 tests failed!"`

On your computer, can this test file run normally?

[2021_03_07__17_44_29__37392.log](https://github.com/KubaP/Powershell-Symlink/files/6096900/2021_03_07__17_44_29__37392.log)

**Comment by KubaP** [comment]
So it seems that you're (probably by default) running that test using Pester `v5`. Currently, those "general" tests which I originally got from somewhere on the internet, require Pester `v4`. For now, before running the `.\build\vsts-validate.ps1` script, run:
```powershell
Import-Module "Pester" -RequiredVersion 4.10.1
```

**Comment by KubaP** [comment]
I've updated the build scripts (0899adbfa2e315c39fca0733477289a87f5940bd) to forcefully load the correct version of Pester, so you should be able to just run `.\build\vsts-validate.ps1` without any issues. I also fixed a few issues in the functions which were failing some tests, so everything should be passing now.

As a side note, I've started to write unit & acceptance tests for the whole module, and all its functions, using Pester `v5`. However, I've ran into an issue with creating symbolic links on the TestDrive within a Pester test (see pester/pester#1863), so for now I'm having to halt progress until this issue can be resolved or worked-around. I also want to rewrite the existing "general" tests to use Pester `v5`.

**Comment by Andy-AO** [comment]
Thanks, I'll try it right away.

In fact, the bug mentioned last time has been fixed, but considering that there is no test, it is not submitted because it is not sure whether it has damaged other parts of the program.

But I don't know how to write tests, so I've been studying in my spare time recently. At present, I feel that I have basically mastered the tools.

It seems that TestDrive is really not easy to use. I feel that it is not irreplaceable. My solution is to directly create a special folder under the source code directory for testing. This special folder is ignored in git, and it is emptied before each test run. I think this effect will be better than that of testdrive because this random folder is really elusive and hard to debug.

I'm glad to hear that you are improving the test and hope it can be completed smoothly.
